# Checkout states
WAITING_NAME = 1
WAITING_PHONE = 2
WAITING_ADDRESS = 3
WAITING_PAYMENT = 4

# Admin Category states
WAITING_CATEGORY_NAME = 10

# Admin Product states
WAITING_PROD_CATEGORY = 20
WAITING_PROD_NAME = 21
WAITING_PROD_IMAGE = 22
WAITING_PROD_PRICE = 23
WAITING_PROD_DESC = 24
WAITING_PROD_QTY = 25
